---
server:
  applicationConnectors:
    - type: http
      port: 11205
  adminConnectors:
    - type: http
      port: 11206

logging:
  level: DEBUG
  appenders:
    - type: file
      currentLogFilename: "/var/log/searchmetrics/sm-n3-job-service/application.log"
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: "/var/log/searchmetrics/sm-n3-job-service/application.%i.log.zip"
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%d{ISO8601} %-5p [%t] %c{1}: %m%n"
      maxFileSize: 10MB
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%d{ISO8601} %-5p [%t] %c{1}: %m%n"

swagger:
  resourcePackage: com.searchmetrics.n3jobservice

cassandra:
  contactPoints: 127.0.0.1
  keySpace: n3jobservice
  port: 9142
